yt

diff --git a/yt b/yt
--- a/yt
+++ b/yt
@@ -4,7 +4,7 @@
 
 # check vlc is available
 type vlc >/dev/null 2>/dev/null || {
-	echo "Couln't find vlc, which is required for this script." >&2
+	echo "Couldn't find VLC, which is required for this script." >&2
 	exit 17
 }
 
